/**
 * 全てのページに適用されるレイアウト
 * TODO
 */
import type { Metadata } from "next";
import "@/app/ui/globals.css";
import Provider from "./Provider";
import Header from "./ui/Header";
import Main from "./ui/Main";
import Footer from "./ui/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja">
      <head />
      <body>
        <Provider>
          <Header />
          <Main>{children}</Main>
          <Footer />
        </Provider>
      </body>
    </html>
  );
}
