/**
 * 全てのページに適用されるレイアウト
 * TODO
 */
import type { Metadata } from "next";
import "@/components/globals.css";
import Provider from "../components/Provider";
import Header from "../components/Header";
import Main from "../components/Main";
import Footer from "../components/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja">
      <head />
      <body>
        <Provider>
          <Header />
          <Main>{children}</Main>
          <Footer />
        </Provider>
      </body>
    </html>
  );
}
